[tool.poetry]
name = "vector-db-benchmark"
version = "0.1.0"
description = ""
authors = ["Kacper ≈Åukawski <kacper.lukawski@qdrant.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
qdrant-client = "^1.5.4"
typer = "^0.6.1"
jsons = "^1.6.3"
h5py = "^3.7.0"
weaviate-client = "^3.24.2"
elasticsearch = "^8.10.0"
pymilvus = "^2.3.1"
redis = "^5.0.1"
ipdb = "^0.13.9"
stopit = "^1.1.2"
opensearch-py = "^2.3.2"
tqdm = "^4.66.1"
clickhouse-connect = "^0.6.23"


[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
pytest = "^7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
