qdrant_python_client_version: "1.14.0"
logging_dir: "/tmp/logs"
working_dir: "/tmp/experiments"
dataset_url: "https://storage.googleapis.com/ann-filtered-benchmark/datasets/dbpedia_openai_100K.tgz"
dataset_name: "dbpedia_openai_100K"
dataset_dim: "1536"
servers:
  - name: "qdrant"
    registry: "ghcr.io"
    image: "qdrant/qdrant"
    version: "dev"
    feature_flags: "false"
  - name: "qdrant"
    registry: "docker.io"
    image: "qdrant/qdrant"
    version: "master"
    feature_flags: "true"
